// School question voices — kid-friendly Kore (female) voice
export const SCHOOL_VOICE_URLS: Record<string, string> = {
  "circletime_1": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/circletime_1.pcm",
  "circletime_2": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/circletime_2.pcm",
  "circletime_3": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/circletime_3.pcm",
  "circletime_4": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/circletime_4.pcm",
  "circletime_5": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/circletime_5.pcm",
  "building_talks_1": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/building_talks_1.pcm",
  "building_talks_2": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/building_talks_2.pcm",
  "building_talks_3": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/building_talks_3.pcm",
  "building_talks_4": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/building_talks_4.pcm",
  "building_talks_5": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/building_talks_5.pcm",
  "tedlets_1": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/tedlets_1.pcm",
  "tedlets_2": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/tedlets_2.pcm",
  "tedlets_3": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/tedlets_3.pcm",
  "tedlets_4": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/tedlets_4.pcm",
  "tedlets_5": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/tedlets_5.pcm",
  "interview_discussion_1": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/interview_discussion_1.pcm",
  "interview_discussion_2": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/interview_discussion_2.pcm",
  "interview_discussion_3": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/interview_discussion_3.pcm",
  "interview_discussion_4": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/interview_discussion_4.pcm",
  "interview_discussion_5": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/interview_discussion_5.pcm",
  "voice_for_change_1": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/voice_for_change_1.pcm",
  "voice_for_change_2": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/voice_for_change_2.pcm",
  "voice_for_change_3": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/voice_for_change_3.pcm",
  "voice_for_change_4": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/voice_for_change_4.pcm",
  "voice_for_change_5": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/voice_for_change_5.pcm",
  "podcast_playground_1": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/podcast_playground_1.pcm",
  "podcast_playground_2": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/podcast_playground_2.pcm",
  "podcast_playground_3": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/podcast_playground_3.pcm",
  "podcast_playground_4": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/podcast_playground_4.pcm",
  "podcast_playground_5": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/podcast_playground_5.pcm",
  "student_council_1": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/student_council_1.pcm",
  "student_council_2": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/student_council_2.pcm",
  "student_council_3": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/student_council_3.pcm",
  "student_council_4": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/student_council_4.pcm",
  "student_council_5": "https://iq1grzgo2lwh6nqd.public.blob.vercel-storage.com/voices/school/student_council_5.pcm",
};
